server:
  port: 8082

spring:
  application:
    name: ANALYTICS-SERVICE
  h2:
    console:
      enabled: true
  datasource:
    username: root
    password: password
    url: jdbc:h2:d:\\analytics
  jpa:
    hibernate:
      ddl-auto: update
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

management:
  endpoints:
    web:
      cors:
        allowed-origins: http://localhost:3000