server:
  port: 8083

spring:
  application:
    name: FEEDBACK-SERVICE
  h2:
    console:
      enabled: true
  datasource:
    username: root
    password: password
    url: jdbc:h2:d:\\feedback
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    hostname: localhost